# Generated by Django 6.1.1 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('specialites_fr', models.TextField(help_text='Spécialités / prises en charge confirmées')),
                ('specialites_en', models.TextField(blank=True)),
                ('interlocuteur', models.CharField(blank=True, max_length=150)),
                ('coordonnees', models.CharField(blank=True, max_length=255)),
                ('canal_transmission', models.CharField(blank=True, max_length=255)),
                ('documents_requis_fr', models.TextField(blank=True)),
                ('documents_requis_en', models.TextField(blank=True)),
                ('processus_etude_fr', models.TextField(blank=True)),
                ('processus_etude_en', models.TextField(blank=True)),
                ('delai_devis_indicatif', models.CharField(blank=True, max_length=150)),
                ('modalites_suivi_fr', models.TextField(blank=True)),
                ('modalites_suivi_en', models.TextField(blank=True)),
                ('conditions_financieres', models.TextField(blank=True, help_text="Conditions/commission lorsqu'elles sont formalisées (usage interne)")),
                ('collaboration_confirmee', models.BooleanField(default=False, help_text='Doit être cochée pour que la clinique apparaisse publiquement sur le site.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cliniques/')),
            ],
            options={
                'verbose_name': 'Clinique partenaire',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('essentiel', 'Document essentiel'), ('complementaire', 'Document complémentaire')], default='essentiel', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('titre_fr', models.CharField(max_length=150)),
                ('titre_en', models.CharField(blank=True, max_length=150)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['type_document', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='EtapeParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titre_fr', models.CharField(max_length=200)),
                ('titre_en', models.CharField(blank=True, max_length=200)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('question_fr', models.CharField(max_length=255)),
                ('question_en', models.CharField(blank=True, max_length=255)),
                ('reponse_fr', models.TextField()),
                ('reponse_en', models.TextField(blank=True)),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PageStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_titre_fr', models.CharField(blank=True, max_length=70)),
                ('meta_titre_en', models.CharField(blank=True, max_length=70)),
                ('meta_description_fr', models.CharField(blank=True, max_length=160)),
                ('meta_description_en', models.CharField(blank=True, max_length=160)),
                ('image_partage', models.ImageField(blank=True, help_text='Image affichée lors du partage sur les réseaux', null=True, upload_to='og/')),
                ('cle', models.SlugField(help_text='ex: accueil, a-propos, mentions-legales', unique=True)),
                ('titre_fr', models.CharField(max_length=200)),
                ('titre_en', models.CharField(blank=True, max_length=200)),
                ('contenu_fr', models.TextField(blank=True)),
                ('contenu_en', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page (texte éditable)',
            },
        ),
        migrations.CreateModel(
            name='PointDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('contenu_fr', models.TextField()),
                ('contenu_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône (lucide-react)", max_length=50)),
                ('titre_fr', models.CharField(max_length=150)),
                ('titre_en', models.CharField(blank=True, max_length=150)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titre_fr', models.CharField(max_length=150)),
                ('titre_en', models.CharField(blank=True, max_length=150)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
