# Generated by Django 6.1.1 on 2026-09-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('pays_residence', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=30, verbose_name='Numero WhatsApp / telephone')),
                ('email', models.EmailField(max_length=254)),
                ('motif', models.CharField(choices=[('orientation', "Demande d'orientation"), ('devis', 'Demande de devis'), ('dossier', 'Envoi de dossier medical'), ('accompagnement', 'Etre accompagne au Maroc'), ('autre', 'Autre')], max_length=20)),
                ('description_probleme', models.TextField(verbose_name='Probleme medical / description libre')),
                ('specialite_recherchee', models.CharField(blank=True, max_length=150)),
                ('budget_indicatif', models.CharField(blank=True, max_length=100)),
                ('periode_souhaitee', models.CharField(blank=True, max_length=150)),
                ('nombre_accompagnants', models.PositiveSmallIntegerField(default=0)),
                ('message_complementaire', models.TextField(blank=True)),
                ('consentement_traitement_donnees', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_etude', 'En etude'), ('orientee', 'Orientee'), ('cloturee', 'Cloturee')], default='nouvelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes_internes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Demande de qualification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='dossiers_medicaux/%Y/%m/')),
                ('libelle', models.CharField(blank=True, help_text='ex: Compte-rendu, Passeport, IRM...', max_length=150)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contact.demandequalification')),
            ],
        ),
    ]
