# Generated by Django 6.1.1 on 2026-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandequalification',
            name='specialite_recherchee',
            field=models.CharField(blank=True, help_text='Une ou plusieurs specialites, separees par des virgules.', max_length=500),
        ),
    ]